<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <Deterministic>true</Deterministic>
    <Authors>Jakob Boman</Authors>
    <Copyright>Copyright (c) Jakob Boman</Copyright>
  </PropertyGroup>
</Project>
