namespace StyleBro.Analyzers;

public static class DiagnosticIds
{
    public const string MemberOrdering = "BRO1001";
    public const string CommentSpacing = "BRO1002";
    public const string EmptyStatement = "BRO1101";
    public const string CombinedAttributes = "BRO1102";
    public const string ConstantOnLeft = "BRO1103";
    public const string DefaultValueConstructor = "BRO1104";
    public const string ConstructorInitializerLine = "BRO1105";
    public const string EmptyString = "BRO1106";
    public const string SplitParametersStartOnNewLine = "BRO1107";
    public const string ParametersOnSameOrSeparateLines = "BRO1108";
    public const string OpenParenthesisOnNameLine = "BRO1109";
    public const string CloseParenthesisOnLastItemLine = "BRO1110";
    public const string ConstraintOnOwnLine = "BRO1111";
    public const string NoRegions = "BRO1112";
    public const string NoRegionsInCodeElements = "BRO1113";
    public const string VariableCasing = "BRO1301";
    public const string ParameterCasing = "BRO1302";
    public const string PrivateFieldNaming = "BRO1303";
    public const string InterfacePrefix = "BRO1304";
    public const string TypeParameterPrefix = "BRO1305";
    public const string FieldPascalCase = "BRO1306";
    public const string FieldPrefix = "BRO1307";
    public const string FieldUnderscore = "BRO1308";
    public const string ElementPascalCase = "BRO1309";
    public const string InheritDocumentation = "BRO1601";
    public const string DocumentationSlashesInComment = "BRO1602";
    public const string DocumentationEndsWithPeriod = "BRO1603";
    public const string PropertySummaryWording = "BRO1604";
    public const string PropertySummaryRestrictedSetter = "BRO1605";
    public const string ConstructorSummary = "BRO1606";
    public const string DestructorSummary = "BRO1607";
    public const string VoidReturnDocumented = "BRO1608";
    public const string PlaceholderElement = "BRO1609";
    public const string EmptyRemarks = "BRO1610";
    public const string ParameterTagsMatch = "BRO1611";
    public const string TrailingComma = "BRO1401";
    public const string BlankLineBeforeOpenBrace = "BRO1501";
    public const string BlankLineBeforeChainedBlock = "BRO1502";
    public const string BlankLineAfterOpenBrace = "BRO1503";
    public const string BlankLineBeforeComment = "BRO1504";
    public const string ElementsSeparatedByBlankLine = "BRO1505";
    public const string BlankLineAfterComment = "BRO1506";
    public const string BlankLinesAtEndOfFile = "BRO1507";
    public const string SingleLineStatementBlock = "BRO1508";
    public const string SingleLineElement = "BRO1509";
}
