# The hand-written part of docs/stylecop-mapping.md. New-Mapping.ps1 combines this with the measured data.
@{
    Status = 'draft (2026-09-30)'

    # For rules the SDK check fixed: which SDK rule or setting did it.
    SdkSettings = @{
        SA1000 = 'IDE0055 formatting'; SA1001 = 'IDE0055 formatting'; SA1002 = 'IDE0055 formatting'; SA1003 = 'IDE0055 formatting'
        SA1007 = 'IDE0055 formatting'; SA1008 = 'IDE0055 formatting'; SA1009 = 'IDE0055 formatting'; SA1010 = 'IDE0055 formatting'
        SA1011 = 'IDE0055 formatting'; SA1012 = 'IDE0055 formatting'; SA1013 = 'IDE0055 formatting'; SA1014 = 'IDE0055 formatting'
        SA1015 = 'IDE0055 formatting'; SA1016 = 'IDE0055 formatting'; SA1017 = 'IDE0055 formatting'; SA1018 = 'IDE0055 formatting'
        SA1019 = 'IDE0055 formatting'; SA1020 = 'IDE0055 formatting'; SA1021 = 'IDE0055 formatting'; SA1022 = 'IDE0055 formatting'
        SA1024 = 'IDE0055 formatting'; SA1025 = 'IDE0055 formatting'; SA1026 = 'IDE0055 formatting'; SA1028 = 'IDE0055 formatting'
        SA1027 = 'IDE0055 formatting (`indent_style = space`)'
        SA1023 = 'IDE0055 formatting'
        SA1209 = 'using sorting in `dotnet format`'; SA1216 = 'using sorting in `dotnet format`'; SA1217 = 'using sorting in `dotnet format`'
        SA1134 = 'IDE0055 formatting'; SA1137 = 'IDE0055 formatting'
        SA1101 = 'IDE0009 (`dotnet_style_qualification_for_* = true`)'
        SA1107 = 'IDE0055 (`csharp_preserve_single_line_statements = false`)'
        SA1119 = 'IDE0047 (`dotnet_style_parentheses_* = never_if_unnecessary`)'
        SA1121 = 'IDE0049 (`dotnet_style_predefined_type_* = true`)'
        SA1200 = 'IDE0065 (`csharp_using_directive_placement = inside_namespace`)'
        SA1208 = 'using sorting in `dotnet format` (`dotnet_sort_system_directives_first = true`)'
        SA1210 = 'using sorting in `dotnet format`'
        SA1211 = 'using sorting in `dotnet format`'
        SA1400 = 'IDE0040 (`dotnet_style_require_accessibility_modifiers = for_non_interface_members`; `always` would also add `public` to interface members, which SA1400 doesn''t ask for)'
        SA1408 = 'IDE0048 (`dotnet_style_parentheses_* = always_for_clarity`)'
        SA1500 = 'IDE0055 (`csharp_new_line_before_open_brace = all`)'
        SA1503 = 'IDE0011 (`csharp_prefer_braces = true`)'
        SA1519 = 'IDE0011 (`csharp_prefer_braces = true`)'
        SA1520 = 'IDE0011 (`csharp_prefer_braces = true`)'
        SA1507 = 'IDE2000 (experimental)'
        SA1508 = 'IDE2002 (experimental)'
        SA1513 = 'IDE2003 (experimental)'
        SA1517 = 'only as a side effect of IDE0073 (file header); not fixed without `file_header_template`'
        SA1633 = 'IDE0073 (`file_header_template`)'
    }

    # Explicit proposals. They override the SDK check result and the default proposal for untested rules.
    Proposals = @{
        SA1504 = 'StyleBro **BRO1510** (done), same positions as StyleCop; the fix decides per property (StyleCop''s applies one direction to the whole project) and keeps comments'
        SA1501 = 'StyleBro **BRO1508** (done). Differs from StyleCop: blocks with a comment inside, and a switch-section block on the line of `switch (x) {`, are not reported'
        SA1502 = 'StyleBro **BRO1509** (done), same positions as StyleCop (local functions reported once, as BRO1509)'
        SX1101 = 'SDK: IDE0003 (`dotnet_style_qualification_for_* = false`); off by default in StyleCop and not enforced by the preset; stylebro-migrate turns IDE0003 on when SX1101 is on'
        SX1309 = 'StyleBro **BRO1303** (done) with `stylebro_private_field_naming = _camelCase`, which stylebro-migrate sets when SX1309 is on'
        SA1412 = 'SDK: `charset = utf-8-bom` (`dotnet format` writes the BOM); off by default in StyleCop and not in the preset; stylebro-migrate sets it when SA1412 is on'
        SA1408 = 'SDK: IDE0048 (`dotnet_style_parentheses_* = always_for_clarity`); fixed only in a separate `dotnet format` pass'
        SA1407 = 'SDK: IDE0048 (`dotnet_style_parentheses_* = always_for_clarity`); fixed only in a separate `dotnet format` pass'
        SA1005 = 'StyleBro **BRO1002** (done), same results as StyleCop 1.2 (1.1.118 also reported `//  two spaces`)'
        SA1106 = 'StyleBro **BRO1101** (done). Differs from StyleCop: embedded (`while (x) ;`) and labeled empty statements are not reported'
        SA1110 = 'StyleBro **BRO1109** (done), same results and output as StyleCop'
        SA1111 = 'StyleBro **BRO1110** (done), same results and output as StyleCop'
        SA1123 = 'StyleBro **BRO1113** (done), same results and output as StyleCop'
        SA1124 = 'StyleBro **BRO1112** (done), off in the preset (StyleCop has it on; opt-in because it''s a large one-time change)'
        SA1127 = 'StyleBro **BRO1111** (done), same results and output as StyleCop'
        SA1116 = 'StyleBro **BRO1107** (done), also checks record and primary-constructor parameters'
        SA1117 = 'StyleBro **BRO1108** (done), also checks record and primary-constructor parameters; unlike StyleCop, has a fix'
        SA1122 = 'StyleBro **BRO1106** (done), same results as StyleCop'
        SA1128 = 'StyleBro **BRO1105** (done), same results as StyleCop'
        SA1129 = 'StyleBro **BRO1104** (done). Differs from StyleCop: `new T()` on a type parameter and `new S();` statements are not reported'
        SA1131 = 'StyleBro **BRO1103** (done). Differs from StyleCop: comparisons using a type''s own operator are not reported'
        SA1133 = 'StyleBro **BRO1102** (done). Differs from StyleCop: lists with comments between attributes are not reported'
        SA1413 = 'StyleBro **BRO1401** (done). Differs from StyleCop: lists with `#if` between their braces are not reported'
        SA1600 = 'StyleBro **BRO1601** (done) for overrides and implementations only (`<inheritdoc/>`); other missing documentation is not reported (no placeholder stubs, user decision)'
        SA1623 = 'StyleBro **BRO1604** (done), same results as StyleCop'
        SA1624 = 'StyleBro **BRO1605** (done), same results as StyleCop'
        SA1626 = 'StyleBro **BRO1602** (done), same results as StyleCop'
        SA1629 = 'StyleBro **BRO1603** (done). Differs from StyleCop: text ending with `?`, `!` or `:` is not reported'
        SA1617 = 'StyleBro **BRO1608** (done), same results and output as StyleCop'
        SA1642 = 'StyleBro **BRO1606** (done), same results as StyleCop (the fix adds a space after the standard sentence)'
        SA1643 = 'StyleBro **BRO1607** (done), same results as StyleCop (the fix adds a space after the standard sentence)'
        SA1651 = 'StyleBro **BRO1609** (done), same results and output as StyleCop'
        SA1612 = 'StyleBro **BRO1611** (done), with a fix (StyleCop has none): stale tags renamed or removed, tags reordered'
        SA1627 = 'StyleBro **BRO1610** (done) for empty remarks, with a fix (removal); StyleCop has none'
        SA1300 = 'StyleBro **BRO1309** (done), rename with Fix All incl. overrides/implementations; namespaces not renamed'
        SA1302 = 'StyleBro **BRO1304** (done), rename with Fix All, same results as StyleCop'
        SA1303 = 'StyleBro **BRO1306** (done), rename with Fix All'
        SA1304 = 'StyleBro **BRO1306** (done), rename with Fix All'
        SA1307 = 'StyleBro **BRO1306** (done), rename with Fix All'
        SA1308 = 'StyleBro **BRO1307** (done), rename to the complete correct name in one pass'
        SA1310 = 'StyleBro **BRO1308** (done), words joined in the field''s casing (MAX_VALUE -> MaxValue)'
        SA1306 = 'StyleBro **BRO1303** (done) for private fields; `stylebro_private_field_naming` picks `count` (default) or `_count`'
        SA1309 = 'StyleBro **BRO1303** (done) for private fields (default style); constants, static readonly and non-private fields not yet'
        SA1311 = 'StyleBro **BRO1306** (done), rename with Fix All'
        SA1312 = 'StyleBro **BRO1301** (done), rename with Fix All; also fixes `_name`'
        SA1313 = 'StyleBro **BRO1302** (done), rename with Fix All incl. named arguments and overrides; also fixes `_name`'
        SA1314 = 'StyleBro **BRO1305** (done), rename with Fix All, same results as StyleCop'
        SA1505 = 'StyleBro **BRO1503** (done), same results as StyleCop'
        SA1509 = 'StyleBro **BRO1501** (done), same results as StyleCop'
        SA1510 = 'StyleBro **BRO1502** (done), same results as StyleCop'
        SA1512 = 'StyleBro **BRO1506** (done), same results as StyleCop'
        SA1515 = 'StyleBro **BRO1504** (done), same results as StyleCop'
        SA1516 = 'StyleBro **BRO1505** (done), same positions as StyleCop'
        SA1518 = 'StyleBro **BRO1507** (done), same results as StyleCop''s default setting'
        SA1201 = 'StyleBro **BRO1001** (done)'
        SA1202 = 'StyleBro **BRO1001** (done)'
        SA1203 = 'StyleBro **BRO1001** (done)'
        SA1204 = 'StyleBro **BRO1001** (done)'
        SA1214 = 'StyleBro **BRO1001** (done)'
    }

    # Paragraphs placed after the candidates table.
    Notes = @(
        '**Observation.** Polly turns off most of StyleCop''s spacing, layout and naming rules and enforces the SDK equivalents instead: 101 IDE rule severities, including IDE0055 (formatting), IDE0011 (braces) and IDE1006 with 10 naming rules, plus `EnforceCodeStyleInBuild`. That is the model StyleBro''s preset follows. All three repos turn off SA1200 (using placement) and SA1401 (fields should be private).'
        '**Naming note.** The SDK can detect all of StyleCop''s naming rules (IDE1006 with naming rules in `.editorconfig`), but `dotnet format` cannot fix them: it reports "Unable to fix IDE1006. Code fix NamingStyleCodeFixProvider doesn''t support Fix All in Solution." A StyleBro rename fix with Fix All would close that gap. Renaming public API breaks callers, so it should start with private and local symbols.'
        'The documentation rules (SA16xx) are mostly not tested yet. The ones where StyleCop has a fix are candidates for the planned BRO16xx rules.'
    )
}
