#!/usr/bin/env pwsh
# Generates docs/stylecop-mapping.md from data/ (inventory, repo surveys, SDK check), repos.psd1 and decisions.psd1.
param([string]$Out = (Join-Path $PSScriptRoot '../../docs/stylecop-mapping.md'))
$ErrorActionPreference = 'Stop'
$data = Join-Path $PSScriptRoot 'data'
$inv = Import-Csv (Join-Path $data 'inventory-1.2.0-beta.556.csv')
$in118 = (Import-Csv (Join-Path $data 'inventory-1.1.118.csv')).Id
$repos = (Import-PowerShellDataFile (Join-Path $PSScriptRoot 'repos.psd1')).Repos
$decisions = Import-PowerShellDataFile (Join-Path $PSScriptRoot 'decisions.psd1')
$check = @{}; Import-Csv (Join-Path $data 'sdk-check.csv') | ForEach-Object { $check[$_.Id] = $_.Verdict }
$invById = @{}; $inv | ForEach-Object { $invById[$_.Id] = $_ }

# Per repo: the effective production setting of each rule ('on', 'info' or 'off') and the counts with every rule on.
$state = @{}; $counts = @{}
foreach ($repo in $repos) {
    $settings = Import-Csv (Join-Path $data "$($repo.Name)-configs.csv")
    $s = @{}
    foreach ($r in $inv) { $s[$r.Id] = if ($r.EnabledByDefault -eq 'True') { 'on' } else { 'off' } }
    foreach ($file in $repo.ProdConfigs) {  # lowest precedence first, so later files win
        foreach ($setting in $settings | Where-Object File -eq $file) {
            $s[$setting.Id] = switch ($setting.Setting) {
                { $_ -in 'none', 'silent', 'hidden' } { 'off' }
                { $_ -in 'suggestion', 'info' } { 'info' }
                default { 'on' }
            }
        }
    }
    $state[$repo.Name] = $s
    $c = @{}; Import-Csv (Join-Path $data "$($repo.Name)-counts.csv") | ForEach-Object { $c[$_.Id] = [int]$_.Diagnostics }
    $counts[$repo.Name] = $c
}
$labels = ($repos | ForEach-Object Label) -join ' / '
$primary = $repos[-1].Name  # the candidates table breaks ties by the last repo's counts

function Get-Proposal($r) {
    if ($decisions.Proposals.ContainsKey($r.Id)) { return $decisions.Proposals[$r.Id] }
    if ($check[$r.Id] -eq 'fixed') { return 'SDK: ' + $decisions.SdkSettings[$r.Id] }
    if ($r.Id -notmatch '^SA\d{4}$') { return 'Variant of another rule (not in 1.1.118 as a separate rule)' }
    if ($r.Category -eq 'DocumentationRules') {
        if ($r.StyleCopHasFix -eq 'True') { return 'Untested. BRO16xx candidate (StyleCop has a fix)' }
        return 'Untested. Likely drop: the fix would need human-written text'
    }
    if ($r.StyleCopHasFix -eq 'True') { return 'Untested. StyleCop has a fix, so a StyleBro fix is feasible' }
    return 'Untested. StyleCop has no fix'
}
function Get-Kept($id) { ($repos | ForEach-Object { $state[$_.Name][$id] }) -join ' / ' }
function Get-Counts($id) { ($repos | ForEach-Object { ([int]$counts[$_.Name][$id]).ToString('n0', [cultureinfo]::InvariantCulture) }) -join ' / ' }
function Get-Check($id) { switch ($check[$id]) { 'fixed' { 'fixed' } 'not-fixed' { 'not fixed' } 'partly' { 'partly' } default { '' } } }

$rows = foreach ($r in $inv) {
    [pscustomobject]@{
        Rule = $r
        Proposal = Get-Proposal $r
        KeptCount = @($repos | Where-Object { $state[$_.Name][$r.Id] -eq 'on' }).Count
        PrimaryCount = [int]$counts[$primary][$r.Id]
    }
}
$tally = [ordered]@{
    SDK = @($rows | Where-Object Proposal -like 'SDK:*').Count
    StyleBro = @($rows | Where-Object Proposal -like 'StyleBro*').Count
    Done = @($rows | Where-Object Proposal -like '*(done)*').Count
    Drop = @($rows | Where-Object Proposal -like 'Drop*').Count
    Untested = @($rows | Where-Object Proposal -like 'Untested*').Count
}
$other = $rows.Count - $tally.SDK - $tally.StyleBro - $tally.Drop - $tally.Untested
$tested = @($check.Keys).Count

$sb = [Text.StringBuilder]::new()
function W([string]$line = '') { [void]$sb.Append($line).Append("`n") }

W '# StyleCop rules and StyleBro'
W
W '<!-- Generated by scripts/stylecop-survey/New-Mapping.ps1. Edit decisions.psd1 or repos.psd1 there, then regenerate. -->'
W
W 'What happens to each StyleCop.Analyzers rule when a project moves to StyleBro. Every rule gets one of three answers:'
W
W '- **SDK**: the .NET SDK already has an equivalent that `dotnet format` fixes. StyleBro''s preset turns it on.'
W '- **StyleBro**: StyleBro provides (or should provide) a rule with a safe automatic fix.'
W '- **Drop**: there is no safe automatic fix, so StyleBro deliberately doesn''t cover it.'
W
W "Status: **$($decisions.Status)**. Of $($rows.Count) rules: $($tally.SDK) SDK, $($tally.StyleBro) StyleBro ($($tally.Done) done), $($tally.Drop) drop, $($tally.Untested) not yet tested, $other not applicable or variants."
W
W '## How this was measured'
W
W 'Scripts and data: [scripts/stylecop-survey](../scripts/stylecop-survey).'
W
W '- **Inventory**: every diagnostic in StyleCop.Analyzers 1.1.118 and 1.2.0-beta.556, read from the analyzer DLLs, including whether StyleCop itself ships a code fix. 1.2.0-beta.556 adds SA1141, SA1142, SA1316, SA1414 and some variants.'
W "- **Teams keeping it on**: the effective setting for production code in $($repos.Count) repos that use StyleCop: $(($repos | ForEach-Object Title) -join ', '). Shown as $labels."
W "- **Diagnostics with every rule on**: each repo built with all StyleCop rules enabled as warnings (and XML docs on), counting unique diagnostics. Shown as $labels. Where a team keeps a rule on, the count is near zero; where it is off, the count shows how much code would change. $(($repos | Where-Object Note | ForEach-Object Note) -join ' ')"
W "- **SDK check**: for $tested rules, a small violating example was formatted with ``dotnet format style`` and ``dotnet format whitespace`` (SDK only, not StyleCop's own fixes) using StyleCop-like SDK settings, and StyleCop was run again. ""fixed"" means the diagnostic was gone. Each rule was checked on one example, so a ""fixed"" rule can still have cases the SDK handles differently."
W
W '## StyleBro candidates, by demand'
W
W "Rules the SDK doesn't cover, ordered by how many of the $($repos.Count) teams keep them on, then by how often they fire in $($repos[-1].Label)."
W
W "| Rule | Title | Teams keeping it on ($labels) | Diagnostics ($labels) | Proposal |"
W '|---|---|---|---|---|'
$rows | Where-Object Proposal -like 'StyleBro:*' |
    Sort-Object @{ E = 'KeptCount'; Descending = $true }, @{ E = 'PrimaryCount'; Descending = $true }, @{ E = { $_.Rule.Id } } |
    ForEach-Object { W ('| {0} | {1} | {2} | {3} | {4} |' -f $_.Rule.Id, $_.Rule.Title, (Get-Kept $_.Rule.Id), (Get-Counts $_.Rule.Id), ($_.Proposal -replace '^StyleBro: ', '')) }
W
foreach ($note in $decisions.Notes) { W $note; W }
W '## All rules'
W
foreach ($cat in ($inv | ForEach-Object Category | Sort-Object -Unique)) {
    W "### $($cat -replace 'Rules$', '')"
    W
    W "| Rule | Title | Default | StyleCop fix | Teams keeping it on ($labels) | Diagnostics ($labels) | SDK check | Proposal |"
    W '|---|---|---|---|---|---|---|---|'
    foreach ($row in $rows | Where-Object { $_.Rule.Category -eq $cat }) {
        $r = $row.Rule
        $id = if ($r.Id -notin $in118 -and $r.Id -match '^SA\d{4}$') { "$($r.Id) (1.2 beta)" } else { $r.Id }
        W ('| {0} | {1} | {2} | {3} | {4} | {5} | {6} | {7} |' -f $id, $r.Title,
            $(if ($r.EnabledByDefault -eq 'True') { 'on' } else { 'off' }), $(if ($r.StyleCopHasFix -eq 'True') { 'yes' } else { 'no' }),
            (Get-Kept $r.Id), (Get-Counts $r.Id), (Get-Check $r.Id), $row.Proposal)
    }
    W
}
[IO.File]::WriteAllText([IO.Path]::GetFullPath($Out), $sb.ToString())
"$([IO.Path]::GetFullPath($Out)): $($rows.Count) rules. SDK $($tally.SDK), StyleBro $($tally.StyleBro), drop $($tally.Drop), untested $($tally.Untested), other $other"
