"""Writes docs/backlog.md: every rule StyleBro has (from README.md and the analyzer release files) and the planned and
"maybe" ones listed below. Edit PLANNED and the "Maybe" tables here, then run from the repository root:
python scripts/New-Backlog.py"""
import re

readme = open('README.md', encoding='utf-8').read()
rows = re.findall(r'^\| \[(BRO\d{4})\]\(docs/rules/BRO\d{4}\.md\) \| (.*?) \| (.*?) \|', readme, re.M)
unshipped = set(re.findall(r'^(BRO\d{4})', open('src/StyleBro.Analyzers/AnalyzerReleases.Unshipped.md').read(), re.M))

PLANNED = [
]

# Work beyond single rules (decided 2026-10-03, see decisions.md "After StyleCop parity"), in this order.
WORK = [
    ('Hardening', 'More real-world repos in the PR pipeline', 'Jellyfin (an application using StyleCop), FluentValidation and CsvHelper (seven target frameworks) added; they found a BRO1302 rename that broke CsvHelper at run time and a BRO1001 blank line that needed a second run.', 'Done (2026-10-03)'),
    ('Hardening', 'IDE0055 in multi-targeted repos', "`dotnet format` crashes in Roslyn's linked-file merge there. `stylebro-migrate format` runs it once per target framework (projects loaded for one framework: nothing to merge); `init` writes IDE0055 at warning everywhere. See decisions.md.", 'Done (2026-10-03)'),
    ('Parity', 'SA1316: tuple element names in PascalCase', 'BRO1311: renamed with every use, literal and override solution-wide (Roslyn\'s Renamer crashes on tuple elements); `stylebro_tuple_element_name_casing`.', 'Done (2026-10-03)'),
    ('Parity', 'SA1108: no comments inside block statements', 'Probe what teams expect first (move the comment above the statement?); StyleCop has no fix.', 'Planned'),
    ('Parity', 'BRO1309: namespace names', 'BRO1312, opt-in (off by default, on through `stylebro-migrate` with SA1300); the root namespace is left out. See docs/proposals/namespace-names.md.', 'Done (2026-10-04)'),
    ('Adoption', 'Getting started', 'docs/getting-started.md: from install to the first `dotnet format` run, for new projects and for StyleCop users; multi-targeted repos and baselines.', 'Done (2026-10-03)'),
    ('Adoption', 'IDE experience', "Check Visual Studio and Rider: light bulbs and Fix All, severities from the preset, `init`'s .editorconfig.", 'Planned'),
    ('Adoption', 'Migration sample', 'samples/StyleCopMigration: a StyleCop-clean project with changed defaults, migrated step by step with real output; `dotnet format` changes no code afterwards.', 'Done (2026-10-03)'),
    ('Beyond StyleCop', 'Survey other analyzers', "Fixable style rules in popular analyzers (e.g. Roslynator's formatting rules) that the SDK doesn't cover; worthwhile ones become rule candidates here.", 'Planned'),
]

blocks = [
    ('10xx', 'Ordering, spacing and comments'),
    ('11xx', 'Readability'),
    ('13xx', 'Naming'),
    ('14xx', 'Maintainability'),
    ('15xx', 'Layout'),
    ('16xx', 'Documentation'),
]

done = len(rows)
out = []
out.append('# Backlog\n')
out.append('<!-- Generated by scripts/New-Backlog.py. Edit the planned and maybe lists there, then run it. -->\n')
out.append('Every style rule StyleBro has or aims to add, with its status, and what\'s left open in existing rules. Update it')
out.append('when work starts or lands; a finished rule also moves from `skipped.psd1` to `decisions.psd1` (see')
out.append('`docs/stylecop-mapping.md`).\n')
out.append('Status: **Released** (on nuget.org), **Done** (on `main`, in the next release), **Planned** (decided, not started),')
out.append('**Maybe** (worth doing if someone asks; why it isn\'t planned is in [skipped-rules.md](skipped-rules.md)).\n')
out.append('## Summary\n')
out.append('| | Rules |')
out.append('|---|---|')
out.append(f'| Released | {done - len(unshipped)} |')
out.append(f'| Done, not released yet | {len(unshipped)} |')
out.append(f'| Planned | {len(PLANNED)} rules, {len(WORK)} work items |')
out.append('| Maybe | none (moved to planned work) |')
out.append('')
mapping = open('docs/stylecop-mapping.md', encoding='utf-8').read()
m = re.search(r'Of (\d+) rules: (\d+) SDK, (\d+) StyleBro .*?, (\d+) drop', mapping)
total, sdk, bro, drop = m.groups()
out.append(f'StyleCop coverage ({total} diagnostics in StyleCop 1.2): {bro} by StyleBro, {sdk} by the .NET SDK, {drop} dropped by design (they')
out.append('can\'t be fixed without inventing text or moving code between files), the rest variants or not applicable. Details in')
out.append('[stylecop-mapping.md](stylecop-mapping.md).\n')

out.append('## Planned\n')
if PLANNED:
    out.append('| ID | Rule | StyleCop | Replaces SDK |')
    out.append('|----|------|----------|--------------|')
    for id, title, sa, ide in PLANNED:
        out.append(f'| {id} | {title} | {sa} | {ide} |')
    out.append('')
else:
    out.append('No new rules planned. The last batch, fix-safe replacements for the SDK rules whose fixes crash `dotnet format`')
    out.append('or write merge conflict markers in multi-targeted projects (decided 2026-10-03, see [decisions.md](decisions.md)),')
    out.append('is done: BRO1514-BRO1516 (IDE0011), BRO1404/BRO1007 (IDE0040), BRO1405-BRO1407 (IDE0047/IDE0048) and')
    out.append('BRO1517-BRO1519 (IDE2000/IDE2002/IDE2003). `init` and `stylebro-migrate` turn those SDK rules off.\n')

out.append('### Work beyond single rules\n')
out.append('StyleCop parity is done apart from the parity items below. Decided 2026-10-03 ([decisions.md](decisions.md)), in this order:\n')
out.append('| Area | Item | Notes | Status |')
out.append('|------|------|-------|--------|')
for area, item, notes, status in WORK:
    out.append(f'| {area} | {item} | {notes} | {status} |')
out.append('')

out.append('### Read the SDK\'s own settings\n')
out.append('Decided 2026-10-03 ([decisions.md](decisions.md)): where the SDK has an `.editorconfig` key for the same choice, StyleBro')
out.append('follows it. Precedence: a `stylebro_*` key, then the SDK key, then StyleCop\'s behavior (today\'s default, unchanged')
out.append('when neither is set). `stylebro-migrate` keeps writing what matches the StyleCop setup.\n')
out.append('| Rules | SDK key | What changes | Status |')
out.append('|-------|---------|--------------|--------|')
for rules, key, change, status in [
    ('BRO1303 (private fields)', '`dotnet_naming_rule.*` / `dotnet_naming_style.*`', 'A naming rule for private fields (required prefix `_`, camel case) picks `camelCase` or `_camelCase` when `stylebro_private_field_naming` isn\'t set (the preset no longer sets it); a style the rule can\'t produce leaves the default. BRO1307 leaves a one-letter prefix a naming rule asks for (`s_`).', 'Done (2026-10-03)'),
    ('BRO1131', '`dotnet_style_qualification_for_method/_property/_field/_event`', '`false` drops `base.` (`Reset()`) instead of writing `this.Reset()`, where the unqualified name binds the same.', 'Done (2026-10-03)'),
    ('BRO1514-BRO1516', '`csharp_prefer_braces`', '`when_multiline`: only multi-line child statements (as IDE0011 counts them) and inconsistent chains; `false`: none.', 'Done (2026-10-03)'),
    ('BRO1404', '`dotnet_style_require_accessibility_modifiers`', '`never`/`omit_if_default`: not reported (removing modifiers is not what these rules do); `always`: interface members too (C# 8+).', 'Done (2026-10-03)'),
    ('BRO1406/BRO1407', '`dotnet_style_parentheses_in_arithmetic_binary_operators` / `_in_other_binary_operators`', '`never_if_unnecessary` turns the rule off (no parentheses added). Removing stays SA1119 (BRO1405): following the SDK\'s broader removal would bring back the `a ?? (b ?? c)` difference in migrated StyleCop repos. `always_for_clarity` keeps StyleCop\'s operator families.', 'Done (2026-10-03)'),
    ('All text fixes', '`end_of_line`', 'Not needed: a full `dotnet format` run normalizes line endings to `end_of_line` in its whitespace pass before the analyzer fixes run, and those copy the file\'s ending.', 'Dropped'),
]:
    out.append(f'| {rules} | {key} | {change} | {status} |')
out.append('')
out.append('IDE0055 (the SDK\'s whole formatter) isn\'t replaced: in multi-targeted repositories `stylebro-migrate format` runs')
out.append('`dotnet format` once per target framework, which avoids the crash. Also to do: report the SDK fixer bugs upstream')
out.append('(dotnet/roslyn).\n')

out.append('## Maybe\n')
out.append('Nothing right now: the last maybes (SA1316, SA1108, namespace names) moved to planned work. Rules worth doing only if')
out.append('someone asks go here.\n')
out.append('The other dropped StyleCop rules (missing documentation, one type per file, ...) are in [skipped-rules.md](skipped-rules.md).\n')

out.append('## All rules\n')
for block, name in blocks:
    prefix = 'BRO' + block[:2]
    out.append(f'### BRO{block}: {name}\n')
    out.append('| ID | Rule | StyleCop | Status |')
    out.append('|----|------|----------|--------|')
    entries = [(id, title, sa, 'Done' if id in unshipped else 'Released') for id, title, sa in rows if id.startswith(prefix)]
    entries += [(id, title, sa, 'Planned') for id, title, sa, _ in PLANNED if id.startswith(prefix)]
    for id, title, sa, status in sorted(entries):
        link = f'[{id}](rules/{id}.md)' if status != 'Planned' else id
        out.append(f'| {link} | {title} | {sa} | {status} |')
    out.append('')

open('docs/backlog.md', 'w', encoding='utf-8', newline='').write('\n'.join(out).rstrip('\n') + '\n')
print(done, len(unshipped))
